<a href="https://colab.research.google.com/github/Raboooiii/Sem6/blob/main/IS/Chi_Square_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('district_level_total_Registered_msme.csv')
df.head()

Saving district_level_total_Registered_msme.csv to district_level_total_Registered_msme (1).csv

,state_name,lg_dist_code,district_name,micro,small,medium,total,last_updated
0,ANDHRA PRADESH,745,Alluri Sitharama Raju,1405,8.0,NaN,1413,2023-08-27
1,ANDHRA PRADESH,744,Anakapalli,7780,89.0,4.0,7873,2023-08-27
2,ANDHRA PRADESH,502,ANANTHAPUR,39107,966.0,56.0,40129,2023-08-27
3,ANDHRA PRADESH,753,Annamayya,9496,101.0,3.0,9600,2023-08-27
4,ANDHRA PRADESH,750,Bapatla,8343,104.0,3.0,8450,2023-08-27

In [4]:
df['small'] = df['small'].fillna(0)
df['medium'] = df['medium'].fillna(0)

In [5]:
observed = [
    df['micro'].sum(),
    df['small'].sum(),
    df['medium'].sum()
]

observed

import numpy as np

total = sum(observed)
expected = [total/3]*3

expected

from scipy.stats import chisquare

chi_stat, p_value = chisquare(f_obs=observed, f_exp=expected)

print("Chi-square Statistic:", chi_stat)
print("P-value:", p_value)

alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis: Distribution is not equal")
else:
    print("Fail to Reject Null Hypothesis: Distribution is equal")

Chi-square Statistic: 33691274.34323555
P-value: 0.0
Reject Null Hypothesis: Distribution is not equal

In [6]:
table = df.groupby('state_name')[['micro','small','medium']].sum()

table.head()

from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square Statistic:", chi2)
print("P-value:", p)
print("Degrees of Freedom:", dof)

alpha = 0.05

if p < alpha:
    print("Reject Null Hypothesis: Enterprise type depends on state")
else:
    print("Fail to Reject Null Hypothesis: Enterprise type is independent of state")

Chi-square Statistic: 70780.39650535684
P-value: 0.0
Degrees of Freedom: 70
Reject Null Hypothesis: Enterprise type depends on state

In [7]:
expected_df = pd.DataFrame(expected,
                           index=table.index,
                           columns=table.columns)

expected_df.head()

                                     micro         small       medium
state_name
ANDAMAN AND NICOBAR ISLANDS    9749.387394    305.931649    28.680957
ANDHRA PRADESH               557298.728465  17487.798184  1639.473351
ARUNACHAL PRADESH              8475.121965    265.945740    24.932296
ASSAM                        286928.222251   9003.686152   844.091597
BIHAR                        733158.959463  23006.217788  2156.822750